### ISSUE TITLE
[JOSS Review]  README.md  minor revisions

### ISSUE THREAD

**Issue by 0todd0000** [tramarobin/fctSPM#13]
1. Community Guidelines: please add a link to the repository's issues page for users who might not be familiar with GitHub issues.  For example:

`Create a new issue in the [Issues section of this repository](https://github.com/tramarobin/fctSPM/issues) to:`

Create a new issue in the [Issues section of this repository](https://github.com/tramarobin/fctSPM/issues) to:

<br>
<br>

2. Statement of Need:  neither "fctSPM" nor "SPM" is defined. I suggest:

> Factorial SPM (fctSPM) allows MATLAB users to create figures of 1D and 2D [SPM](https://spm1d.org) analysis for ANOVA and post-hoc designs.

**Comment by tramarobin** [comment]
Thank you for the suggestions, the README.md file was modified accordingly.

**Comment by 0todd0000** [comment]
Thank you.
