### ISSUE TITLE
Interaction post-hoc and Number of t-tests

### ISSUE THREAD

**Issue by jinhee615** [tramarobin/fctSPM#15]
Hello. I'm trying to make a 3x3 (Group x Condition) two way repeated ANOVA post hoc.

I was wondering, why there are only 18 t-tests for post hoc.
I thought, There are total 9 dataset (3x3). And I should choose two of them regardless of its order, so 9*8/2=36 t-test is needed.

For example, I have 3 Groups named N,I,O, and 3 Conditions with same name of N, I, O.
So there are 9 Groups and Data like below : 
![image](https://user-images.githubusercontent.com/82136393/116092985-41fec480-a6e1-11eb-9e6b-15aadec06af8.png)

I thought should have 36 t-tests like below.
1.II-IN
2.II-IO
3.II-NI
4.II-NN
5.II-NO
6.II-OI
7.II-ON
8.II-OO
9.IN-IO
10.IN-NI
11.IN-NN
12.IN-NO
13.IN-OI
14.IN-ON
15.IN-OO
16.IO-NI
17.IO-NN
18.IO-NO
19.IO-OI
20.IO-ON
21.IO-OO
22.NI-NN
23.NI-NO
24.NI-OI
25.NI-ON
26.NI-OO
27.NN-NO
28.NN-OI
29.NN-ON
30.NN-OO
31.NO-OI
32.NO-ON
33.NO-OO
34.OI-ON
35.OI-OO
36.ON-OO
 
But there were only 18 t-tests were observed.

II-IN, II-IO, II-NI, II-OI
IN-IO, IN-NN, IN-ON
IO-NO, IO-OO
NI-NN, NI-NO, NI-OI
NN-NO, NN-ON
NO-OO
OI-ON, OI-OO, ON-OO

Were there any reason only 18 t-tests were exists?

**Comment by tramarobin** [comment]
Hello, 

The comparisons performed with this function are between the data that shares a commun factors (either their belong to the same group, or have performed the same condition). On your graph, only the comparisons between the elements of a same row or column are performed. This is why II and ON are not compared for instance, as they share neither their group or condition.

In don't know if it has a statistical logic to do so, as the two effects are involved at the same time and the result of the ttest can not be interpreted as a main effect nor an interaction effect.

**Comment by jinhee615** [comment]
> The comparisons performed with this function are between the data that shares a commun factors

So t-test post hoc is comparsion within groups or within conditions.

> In don't know if it has a statistical logic to do so, as the two effects are involved at the same time and the result of the ttest can not be interpreted as a main effect nor an interaction effect.

So you mean, post hoc t-tests are not capable of interpreting two-way ANOVA interaction or main effects?
If it's so, How Can I interpret interaction? by which static data?

![image](https://user-images.githubusercontent.com/82136393/116102851-04eb0000-a6ea-11eb-9812-6db2e84a2bc0.png)

Above graphs exhibits Group x Condition interaction. and 11th t-test (NI vs NO) showed significance like below.
![image](https://user-images.githubusercontent.com/82136393/116103435-8b9fdd00-a6ea-11eb-8de6-7a9cf4000dd1.png)


May I ask you How to interpret it?

Sorry for I feel like bothering you with similar issue, But I need your help.
Thank you in advance.

**Comment by tramarobin** [comment]
> So t-test post hoc is comparison within groups or within conditions.

Yes. More precisely for interactions, a comparison within group for a specific condition or a comparaison within conditions for a specific group.

> May I ask you How to interpret it?

As I wrote in issue #12, there are 3 important results here for me :

There is a significant difference at the start of the stand phase (0-20%) with Outtoed > Intoed only for the N group (Interaction effect)
There is a significant difference between 25 and 30% of the stance phase with Outtoed > Intoed for all groups (main Condition effect)
There is a significant difference at the end of the stance phase with Outtoed > Intoed (90-100%) and Outtoed > Normal (95-100%) for all groups (main Condition effect).

However, the data you presented here does not inform if there is a group effect, nor if the interaction depicted by the ANOVA led to a different group effect within each condition.


> Sorry for I feel like bothering you with similar issue, But I need your help.

No worries, always happy to help.

**Comment by jinhee615** [comment]
> the result of the ttest can not be interpreted as a main effect nor an interaction effect.
You mean, to interpret main effect, using SPM post-hoc ttest results are not appropriate?

 
![image](https://user-images.githubusercontent.com/82136393/116168503-81f39500-a73d-11eb-8dbf-3db01758306c.png)

to interpret Condition main effects in above image, I get the clusters through codes below.
spmAnalysis2.posthoc{1,2}.tTests.clusterLocation{1,1}
spmAnalysis2.posthoc{1,2}.tTests.clusterLocation{1,2}
spmAnalysis2.posthoc{1,2}.tTests.clusterLocation{1,3}
spmAnalysis2.posthoc{1,2}.tTests.clusterP




![image](https://user-images.githubusercontent.com/82136393/116166470-0bed2f00-a739-11eb-9a27-91c876348b71.png)
Above Image showed How I interpreted Interaction.
Although interaction post hoc ttests exhibited significance from middle~end of the stance phase, ANOVA interaction reported Significant difference in 95~100%, So I reported results only for 95~100% regardless of post hoc t-test results.
But I think it is like condition main effects, not a Interaction.
Above image is appropriate interpretation?

Thanks always. :) !

**Comment by tramarobin** [comment]
> the result of the ttest can not be interpreted as a main effect nor an interaction effect.
You mean, to interpret main effect, using SPM post-hoc ttest results are not appropriate?

No I just meant in the case you compared data of different Group AND Condition (e.g., IO and NN). It's ok to interpret main effects at the locations where there is no interactions.

> Above Image showed How I interpreted Interaction.
> Although interaction post hoc ttests exhibited significance from middle to end of the stance phase, ANOVA interaction reported Significant difference in 95-100%, So I reported results only for 95~100% regardless of post hoc t-test results.
> But I think it is like condition main effects, not a Interaction.
> Above image is appropriate interpretation?

Your interpretation of the interaction is correct.
You must also report the main effect on 51-95% as there is no interaction at these locations. That's maybe why the lack of differences on 95-100% (different from the main effect) are maybe more relevant than the interactions that agree with the main effect. Consequently, I'd rather present the main effect on 51-100%, and explain where the interaction disagrees with the main effect. 

For instance, one way do to so can be : 
There was a main effect on 51-100% on the stance phase (p=0.03), with O > I (55-100%, p=...), O > N (68-100%) and N > I (68-100%). However, a interaction effect occurred on 95-100% (p=0.049). On this portion of the stance phase, O = N for the I and N groups, while the difference is still present on 98-100% for the O group. (...)

You should avoid to use "-" in the name of the effect (e.g., `Intoe-Condition` should be `Intoe Condition`). The sign "-" is used in the function to determine the name of the differences and that's why the names are not displayed correctly. [See here for some cautions](https://github.com/tramarobin/fctSPM#caution)

**Comment by jinhee615** [comment]
I have one more similar Question.

There were Group x Condition Interaction in Hip abduction angle.
ANOVA result showed significance in 11%~70%.

![image](https://user-images.githubusercontent.com/82136393/116239455-9f584b80-a79d-11eb-9c17-ec3e73786d13.png)

I want to interpret interaction in this case, But it is confused too.

1). There were interaction between II vs IO, IN vs IO, / NI vs NN, NI vs NO, NN vs NO in 11-70% Stance phase
So I considered differences only in 11-70%, and ignored others(diffences in 0~11%, 70~100% are ignored)

2) in early interaction phase, IO exhibits larger Hip abduction Angle than II, IN. and NO group exhibits larger hip abd angle than NN.

3) at the end of the interaction effect phase, NI exhibits larger Hip abd angle than NN, NO.

4). There was condition main effect on 0-100% stance phase with I>N(44~91%), I>O(0~28, 64~82%),  N>O(0~50, 87~100%). And Interaction effect occurred on 11~70%. I group exhibits larger Hip abduction angle in condition O than I,N in early interaction phase, and N group exhibits larger Hip abduction Angle in condition O than N in early interaction phase, while I condition showing larger hip abduction angle than conditions N and O in late stance phase.


Is (4) is right interpretation for those interactions? Or do I need to refer SPM{t} Graphs? or above graphs are enough?

Thanks a lot!

**Comment by tramarobin** [comment]
> Is (4) is right interpretation for those interactions?

Yes but I would precise the % of the stance phase at which the differences occurred : 

And Interaction effect occurred on 11-70%. I group exhibits larger Hip abduction angle in condition O than I (0-32%), and than N (0-52%). 

> Or do I need to refer SPM{t} Graphs? or above graphs are enough?

I think above graphs are enough and synthetize the idea. One can clearly identify where the differences occurred.
However, this representation is not common (yet), and reviewers might demand other graphs.

**Comment by jinhee615** [comment]
Thanks!
