### ISSUE TITLE
Main Effect interpretation

### ISSUE THREAD

**Issue by jinhee615** [tramarobin/fctSPM#16]
Hello. I have 3x3 Group x Condition design with two way repeated measures.

two way ANOVA revealed Condition main effect, and Post hoc was conducted.
There is a condition main effect, however, No t-test significance are shown like image below.

![image](https://user-images.githubusercontent.com/82136393/116249962-4641e500-a7a8-11eb-8211-72e6ae6649cd.png)

How Can I interpret it? what kind of main effect it is, and Which condition exhibited main effect?

**Comment by tramarobin** [comment]
There is potentially a Condition effect, however, the post hoc test is not powerful enough to detect significant changes in conditions.

**Comment by jinhee615** [comment]
Does fctSPM post-hoc ttest use Bonferroni correction?

**Comment by tramarobin** [comment]
Yes it does.

`spmAnalysis.posthoc.tTests.pBonferroni` is the alpha risk choosen for the post hoc tests after Bonferroni correction.

**Comment by jinhee615** [comment]
Thank You so much!
