### ISSUE TITLE
Changed Value of interaction section

### ISSUE THREAD

**Issue by jinhee615** [tramarobin/fctSPM#17]
Hello!

I have 3x3 two-way ANOVA design, And I wonder why interaction section value changed when I run same code twice.

With spm1d code (spm1d.stats.anova2onerm(Y1, Group, condition, subj))
Interaction clusters were found in 0-14%, 18-28%, 85-88%, 96-100% Like Image below.
![image](https://user-images.githubusercontent.com/82136393/117156107-52592280-adf8-11eb-9e89-0259ff1ce86f.png)

When I run fctSPM, Interaction section was different. and it changed over trials.
![image](https://user-images.githubusercontent.com/82136393/117155573-d8289e00-adf7-11eb-8c12-02e1d790da5e.png)
Upper one is the first trial, and Under one is second trial with exactly same code and same condition. But the result was changed.
  
My code was spmAnalysis2=fctSPM(Y3,independantEffects, repeatedMeasuresEffects, 'effectsNames', effectNames) for above graphs. Which one is more reliable? And why those differences were occurred?

+
I tried other code 
spmAnalysis2=fctSPM(Y3,independantEffects, repeatedMeasuresEffects, 'effectsNames', effectNames, 'multiiT', 500 , 'maximalIT', 20000);
three times and 3 results were different.
![image](https://user-images.githubusercontent.com/82136393/117159599-60f50900-adfb-11eb-8820-111219c31259.png)

**Comment by tramarobin** [comment]
Hi,

It happens when the number of iterations is to small. 
You should (must) increase the number of iterations with the input 'multiIT' as it defines the number of permutations as multiIT/alpha. Default is 10, corresponds to 200 iterations for 5% risk. 

When there are more iterations (the more is the better) the analysis is more reproductible and gives the same results. 

By default the number of maximal iterations is 10 000. But you can increase it with the input 'maximalIT'. 

It really depends on your computer but in one dimension, 20 000 iterations run quite smoothly.

**Comment by jinhee615** [comment]
Even I increase 20 000 iterations, SPM1d and fctSPM exhibits different % section of interaction (I uploaded 3 images at the end of above questions). How can I handle it?

**Comment by tramarobin** [comment]
Oh sorry didn't watch the end of yourmessage. 

Classic SPM analysis is parametric while a non parametric approach is used in this function, that can explain the discrepancies between the methods. 
As the t-value is very close to the threshold and that post-hoc with Bonferonni correction is only approximate, I would interpret the results with caution. 

Maybe try with even more iterations but i doubt the results will be really different.

**Comment by jinhee615** [comment]
If I want to use only fctSPM, is there any function to check where significant main effect or interaction location? ( exact % point of significance ) and its p-value? 

I ve been run Classic spm analysis and fctSPM both. I took main effect and interaction clusterds by SPM, and took post hoc and graphs. But if those differencee appears again, maybe i must choose between one of them, which one is more reliable to me. But I really like fctSPM graphs, I want to use it if it s possible.

 And You told me fctSPM use non parametric method, But my data is  following timeseries, continuous. Is it appropriate to use fctSPM ?

**Comment by tramarobin** [comment]
> If I want to use only fctSPM, is there any function to check where significant main effect or interaction location? ( exact % point of significance ) and its p-value?

For the ANOVA, you can find location and p-value in `spmAnalysis.anova`
* `clusterLocation` is a structure (one for each significant cluster) that contains the location (start and end as indexes) of each significant cluster.
* `clusterP` is a structure (one for each significant cluster) that contains the p-value of each significant cluster.

For the post hoc, you can find location and p-value in `spmAnalysis.posthoc` 
* `tTests.clusterLocation `is a structure (one for each significant cluster) that contains the location (start and end as indexes) of each significant cluster.
* `tTests.clusterP` is a structure (one for each significant cluster) that contains the p-value of each significant cluster. This value is corrected with inverse Bonferonni correction. 
 
For posthoc, the clusters are not corrected with the result of the ANOVA (only the t-test is considered).

> And You told me fctSPM use non parametric method, But my data is following timeseries, continuous. Is it appropriate to use fctSPM ?

The non parametric approach of SPM uses permutation tests, which allow to calculate the threshold (F and t) based on the distribution of the statistical test. If you haven't yet, you can read [Nichols TE, Holmes AP (2002). Nonparametric permutation tests for functional neuroimaging: a primer with examples. Human Brain Mapping 15(1), 1–25.](https://pubmed.ncbi.nlm.nih.gov/11747097/)

Even if your data are normally distributed, the permutation will calculate and define a threshold close to the parametric approach. However, it can still have differences. This method is appropriate and more flexible than the parametric approach.

> I ve been run Classic spm analysis and fctSPM both. I took main effect and interaction clusterds by SPM, and took post hoc and graphs. But if those differencee appears again, maybe i must choose between one of them, which one is more reliable to me. But I really like fctSPM graphs, I want to use it if it s possible.

You should use one methodology and not mix between them. It is the same for every statistical tests, how reporting the "close to significant" is often not easy.

**Comment by jinhee615** [comment]
Thank you so much for your kind answer! :)
