### ISSUE TITLE
Function's name

### ISSUE THREAD

**Issue by tramarobin** [tramarobin/fctSPM#21]
@nicholst & @0todd0000, thank you for your review and insights on this function.

I was just wondering if fctSnPM, for Statistical nonParametric Mappping, would not be more appropriate name for this function as the approach use to perform the statistical inferences is non-parametric.

If you are ok with this change, I'll modify the different files to be with the same name.

**Comment by nicholst** [comment]
Im biased, but, yes I think this is an excellent proposal. :)

**Comment by 0todd0000** [comment]
I agree, good suggestion!

**Comment by tramarobin** [comment]
Ok thank you for your feedbacks.
