### ISSUE TITLE
[JOSS Review] Installation instructions for novice MATLAB users

### ISSUE THREAD

**Issue by 0todd0000** [tramarobin/fctSPM#3]
Please provide slightly more detailed installation instructions for novice users who might not understand paths and/or how to add specific directories to the MATLAB path.

**Comment by tramarobin** [comment]
The instructions were modified including 2 different lines of code to add the specific path.

**Comment by 0todd0000** [comment]
For the installation instructions, instead of this:

> To add source code directory to your path use addpath(genpath("./fctSPM/src"))
If your are running examples from ./fctSPM/Examples, you can use addpath(genpath("../src")) to add the source code directory to your path


I suggest:


> Install this package by adding the `src` directory and its subdirectories to the MATLAB path. One way to do this is to call: `addpath(genpath("./fctSPM/src"))`, where `./fctSPM/src` is the full path to the `src` directory. Refer to the [MATLAB documentation regarding search paths](https://www.mathworks.com/help/matlab/matlab_env/add-remove-or-reorder-folders-on-the-search-path.html) for alternative ways to set the path for current and future sessions.


As in issue #2, please do not perform installation procedures in the package demonstration scripts.

**Comment by tramarobin** [comment]
Thank you for the suggestion, the documentation was modified. 

Concerning the issue #2, I will delete the concerned lines (I'll answer in the issue #2 when it is done and uploaded.)

**Comment by 0todd0000** [comment]
Thank you.

In the online documents please change `/fctSPM/src` to `./fctSPM/src`.

If the command were `addpath(genpath("x"))`, when citing `x` outside of this command it should exactly match what is inside the quotes to avoid confusion.

**Comment by tramarobin** [comment]
It was modified, sorry for the typo.

**Comment by 0todd0000** [comment]
OK, thank you.
