### ISSUE TITLE
[JOSS Review]  Output explanation

### ISSUE THREAD

**Issue by 0todd0000** [tramarobin/fctSPM#5]
The scripts generate a number of output files, but these outputs are explained in neither the online documentation nor in `fctSPM.m`.  Please add an explanation of outputs, preferably both to the online documentation and to `fctSPM.m`.

**Comment by tramarobin** [comment]
Output descriptions was added in  `fctSPM.m` and on the online documentation

**Comment by 0todd0000** [comment]
OK.  The online documentation states `anova.m`, but I cannot find this file. Should this be `ANOVA.mat`?

**Comment by 0todd0000** [comment]
Similarly, I can not find a `posthoc.m` file. This should probably be `posthoc.mat`.  Please change `.m` to `.mat` in the online documentation and in the source code comments.

**Comment by tramarobin** [comment]
Sorry you are wright, the files are `anova.mat` in the ANOVA folder and  `posthoc.mat` in the Post hoc folder. 

This was modified in the online documentation and in `fctSPM` documentation as well.

**Comment by 0todd0000** [comment]
OK, thank you.
