### ISSUE TITLE
[JOSS Review]   Suggestion: spm1d dependency

### ISSUE THREAD

**Issue by 0todd0000** [tramarobin/fctSPM#7]
Please consider removing `spm1d_Pataky` from the repository, and instead listing it as a third-party requirement of this package.

The `spm1d` source code gets updated periodically with additional features and bug fixes, and the easiest way to propagate those changes to `fctSPM` would probably be to update `fctSPM`-specific code as needed, rather than manually update `spm1d_Pataky`.

If you choose to keep `spm1d_Pataky` in this repository, please note in the manuscript that `spm1d_Pataky` is published elsewhere, and thus is not part of this JOSS review.

**Comment by tramarobin** [comment]
I think it would be easier to let the pacage inside the repository.
I modified the manuscript accordingly (lines 34-36) : 
[updated Manuscript.pdf](https://github.com/tramarobin/fctSPM/files/6309893/updated.Manuscript.pdf)

**Comment by 0todd0000** [comment]
OK. Please change:  "integrated in the fctSPM repository" to "redistributed with fctSPM".

(No customizations appear to have been applied to the spm1d source code, so I think "redistributed" is more appropriate than "integrated".)

**Comment by tramarobin** [comment]
This has been changed in the article. Indeed, no modification of the spm1d package has been made.

**Comment by 0todd0000** [comment]
OK, thank you.
