### ISSUE TITLE
[JOSS Review]  post hoc p values corrections?

### ISSUE THREAD

**Issue by 0todd0000** [tramarobin/fctSPM#9]
Are post hoc probability values corrected (i.e., using the inverse Bonferroni correction)?

I can't seem to find this correction in the code.

For example, in the `Speed.mat` outputs for `D1_ANOVA1rm.m` I can find probability values in the `clustersT` cell array, but it is unclear whether these have been corrected. 

Note that this is a minor issue, as the corrected p values will be `alpha` at most, but it's nevertheless important to ensure that p values aren't misleadingly low.

**Comment by tramarobin** [comment]
The outputs were reorganized and you can find the probabilities for each test and each cluster in the `anova.mat` file at `anova.clusterP{test}(cluster)` and in the `posthoc.mat` file at  `posthoc.tTests.clusterP{test}(cluster)`

The probabilities are now corrected as suggested with the inverse Bonferroni correction for the ANOVA and the post hoc tests. 
It is indeed better if the values are not misleading.

**Comment by 0todd0000** [comment]
OK. I see, for example that Line 108 in fctPostHoc1d.m implements this:

```
posthoc.tTests.clusterP{comp}(c)=clustersT{c}.P*nComp;
```

This is fine, but now the problem with `nT` and `alphaT` becomes even more important. Now conceivably the user could specify `nT` as much smaller than `nComp`, and artificially lower p values.  The relation amongst `alpha`, `alphaT`, `nComp` and `nT` is very confusing, and I am concerned that it may even be invalid. We have started to discuss this issue in #8, so I will paraphrase this comment there and close this issue.
